services:

  db:
    image: postgres:17-alpine
    container_name: budget-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d budget_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: budget-backend
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://db:5432/budget_db
      - DB_USER=user
      - DB_PASSWORD=postgres

#  frontend:
#    container_name: budget-frontend
#    build:
#      context: ./frontend
#    restart: unless-stopped
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    environment:
#      - CHOKIDAR_USEPOLLING=true

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: